# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("height: 30;\n"
"margin: 30;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginLabel.setScaledContents(False)
        self.loginLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_3.addWidget(self.loginLabel)
        self.loginLine = QtWidgets.QLineEdit(self.centralwidget)
        self.loginLine.setInputMask("")
        self.loginLine.setObjectName("loginLine")
        self.verticalLayout_3.addWidget(self.loginLine)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.passLabel = QtWidgets.QLabel(self.centralwidget)
        self.passLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.passLabel.setObjectName("passLabel")
        self.verticalLayout_4.addWidget(self.passLabel)
        self.passLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passLine.setObjectName("passLine")
        self.verticalLayout_4.addWidget(self.passLine)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.loginLabel.setText(_translate("MainWindow", "Введите номер:"))
        self.passLabel.setText(_translate("MainWindow", "Введите пароль:"))
        self.startButton.setText(_translate("MainWindow", "Готово"))
